# the docs for all these setting is avilable at: https://docs.ligo.org/RatesAndPopulations/gwpopulation_pipe/ 

# user genral settings 
run-dir=run_folder 
log-dir=run_folder/logs
label=gwtc5_sub_populations

# This option is only relevant if you are running on a cluster that requires
user=nir.guttman
# vt file
vt-file=data/mixture-semi_o1_o2-real_o3_o4a_o4b-cartesian_spins_20260410130052UTC-clipped.hdf
vt-ifar-threshold=1.0
vt-snr-threshold=10.0
vt-function=injection_resampling_vt
# specify the prior file 
prior-file=run.prior
# cluster HW request
request-gpu=1
require-gpus=(Capability>=8.0) && (DriverVersion>=13)

backend=jax
cosmo=False
cosmology=Planck15_LAL
container=None
conda-env=None
pool=osg

## models
all-models={
    mass: [ThreePeaks_mass_models.TwoPeakBrokenPowerLawSmoothedMassDistribution],
    redshift: [gwpopulation.models.redshift.PowerLawRedshift],
    spin: [effective_spin_chi_model.EffectiveSpinChiEffChiP]
}
source-files=[models/ThreePeaks_mass_models.py, models/effective_spin_chi_model.py]


## Data collection arguments
existing-data-directory=/fail

parameters=[mass_1, mass_ratio, chi_eff, chi_p, redshift]
ignore=[GW170817, S190425z, GW200115, 190403, 230518, GW191204_110529, GW200208_222617, 230529, GW190425_081805, 190426, 190514, GW190814, 190916, GW190917, 190926, 191113, 191126, GW191219, 200105, 200115, 200210, 200220, 200306, 200308, 200322]
sample-regex={GWTC2.1: GWTC-2.1/*_cosmo.h5, GWTC3: GWTC-3/IGWN-GWTC3p0-v1-GW*_cosmo.h5, GWTC4: GWTC-4/IGWN*.hdf5, GWTC5:GWTC-5/*.hdf5}
preferred-labels=[C00:NRSur7dq4, C01:Mixed, C00:Mixed, C00:IMRPhenomXPHM-SpinTaylor]


# additional settings 
plot=True
n-simulations=None
samples-per-posterior=5000
collection-seed=None
data-label=posteriors
distance-prior=comoving
mass-prior=flat-detector-components
spin-prior=component
custom-parameter-mapping=None
sampler=dynesty
sampler-kwargs={'sample': 'acceptance-walk', 'nlive': 1000, 'dlogz': 0.1, 'naccept': 10}
vt-parameters=[mass, redshift, spin]
periodic-restart-time=42600
enforce-minimum-neffective-per-event=False
maximum-uncertainty=1
max-redshift=1.9
minimum-mass=3.0
maximum-mass=300.0

