run-dir = demo/outdir
label = tiny_demo

# skipping vt for this demo
#vt-file = data/injections/mixture-semi_o1_o2-real_o3_o4a_o4b-cartesian_spins_20260410130052UTC-clipped.hdf
#vt-ifar-threshold=1.0
#vt-snr-threshold=10.0
#vt-function=injection_resampling_vt


data-label = posteriors
plot = False
backend=jax
## models - doesnt work for strandalone run only for clusters 
all-models={
    mass: [ThreePeaks_mass_models.TwoPeakBrokenPowerLawSmoothedMassDistribution],
    redshift: [gwpopulation.models.redshift.PowerLawRedshift],
    spin: [effective_spin_chi_model.EffectiveSpinChiEffChiP]
}
source-files=[demo/models/ThreePeaks_mass_models.py,models/effective_spin_chi_model.py]

## Data collection arguments, use only 5 events
existing-data-directory=/fail

parameters=[mass_1, mass_ratio, chi_eff, chi_p, redshift]
ignore=[GW170817]
sample-regex={GWTC2.1: data/GWTC-2.1/*_cosmo.h5}
preferred-labels=[C00:NRSur7dq4, C01:Mixed, C00:Mixed, C00:IMRPhenomXPHM-SpinTaylor]

prior-file=demo/config/demo.prior


collection-seed=None
distance-prior=comoving
mass-prior=flat-detector-components
spin-prior=component
custom-parameter-mapping=None
sampler=dynesty
sampler-kwargs={'sample': 'acceptance-walk', 'nlive': 300, 'dlogz': 1, 'naccept': 10}
vt-parameters=[mass, redshift, spin]
samples-per-posterior = 200
enforce-minimum-neffective-per-event=False
maximum-uncertainty=1
max-redshift=1.9
minimum-mass=3.0
maximum-mass=300.0





